import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { useApp } from '../../context/AppContext';
import Card from '../ui/Card';
import StatusBadge from '../ui/StatusBadge';
import ProgressBar from '../ui/ProgressBar';
import { 
  Download, 
  Eye, 
  RefreshCw, 
  FileText, 
  Presentation, 
  Headphones, 
  Share2, 
  Hash, 
  GitBranch, 
  BarChart3, 
  Play, 
  Pause, 
  Volume2, 
  Copy, 
  Check, 
  ExternalLink, 
  Clock, 
  ChevronDown, 
  ChevronUp, 
  FileBarChart,
  ArrowRight,
  Package,
  Loader2
} from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import mermaid from 'mermaid';
import './OutputPage.css';
import { useLanguage } from '../../context/LanguageContext';
import html2pdf from 'html2pdf.js';
import { marked } from 'marked';
import PptxGenJS from 'pptxgenjs';

// Initialize mermaid with explicit dark mode theming
// Use 'base' theme + custom variables (not 'dark' which overrides our colors)
// Disable htmlLabels so labels render as SVG <text> elements (easier to style)
mermaid.initialize({ 
  startOnLoad: false, 
  theme: 'base',
  themeVariables: {
    darkMode: true,
    background: '#0f172a',
    primaryColor: '#1e3a5f',
    primaryTextColor: '#e2e8f0',
    primaryBorderColor: '#3b82f6',
    lineColor: '#64748b',
    secondaryColor: '#1e293b',
    tertiaryColor: '#0f172a',
    nodeBorder: '#3b82f6',
    mainBkg: '#1e3a5f',
    nodeTextColor: '#e2e8f0',
    textColor: '#e2e8f0',
    labelTextColor: '#e2e8f0',
    clusterBkg: '#0f172a',
    clusterBorder: '#334155',
    edgeLabelBackground: '#1e293b',
    fontSize: '14px'
  },
  flowchart: {
    htmlLabels: false,
    useMaxWidth: true,
    curve: 'basis'
  }
});

// Clean up mermaid code that models sometimes produce with issues
const cleanMermaidCode = (raw) => {
  if (!raw) return '';
  let code = raw;
  
  // Strip reasoning blocks generated by models like DeepSeek-R1. 
  // We remove anything from <think> to </think>. If unclosed, we remove from <think> to the first ```
  code = code.replace(/<think>[\s\S]*?(<\/think>|```|$)/gi, (match, p1) => p1 === '```' ? '```' : '').trim();
  
  // Extract mermaid code from markdown code block if wrapped in one.
  // IMPORTANT: Reasoning models (like nemotron-super) output chain-of-thought text
  // that may contain ``` backtick references BEFORE the actual code block.
  // We must find the code block that contains a valid diagram declaration,
  // not just the first ``` we encounter.
  const allBlocks = [...code.matchAll(/```(?:mermaid)?\s*([\s\S]*?)(?:```|$)/g)];
  const diagramPattern = /^\s*(flowchart|graph|mindmap|pie|journey|gantt|sequenceDiagram|classDiagram)\b/m;
  
  let bestBlock = null;
  for (const block of allBlocks) {
    if (diagramPattern.test(block[1])) {
      bestBlock = block[1].trim();
      break;
    }
  }
  // Fallback: if no block has a diagram declaration, use the last block (most likely the actual code)
  if (!bestBlock && allBlocks.length > 0) {
    bestBlock = allBlocks[allBlocks.length - 1][1].trim();
  }
  if (bestBlock) {
    code = bestBlock;
  }
  
  // Clean up any loose backticks and extra whitespace
  code = code.replace(/```\w*/g, '').trim();

  // IMPORTANT: Do NOT convert \n to actual newlines, as this breaks indentation hierarchies in mindmaps.
  // Convert them to <br/> tags so they render visually as newlines but remain syntactically on one line.
  code = code.replace(/\\n/g, '<br/>');
  
  // Strip the word 'mermaid' if the LLM outputted it without backticks
  code = code.replace(/^mermaid\s*/i, '');

  // Auto-fix common LLM syntax mistakes
  code = code.replace(/^flowchart LX\b/gmi, 'flowchart LR');
  
  // Escape HTML-unsafe characters that crash Mermaid's DOM renderer
  // & is interpreted as HTML entity start — replace with 'and'
  code = code.replace(/&/g, 'and');
  
  // Fix malformed arrows (e.g., -> instead of -->)
  code = code.replace(/([^.-])->([^.-])/g, '$1-->$2');

  // Fix spaces around ::: for class definitions
  code = code.replace(/\s+:::\s*/g, ':::');
  
  // Remove trailing semicolons on node definitions if they have classes
  code = code.replace(/:::[A-Za-z0-9_-]+\s*;/g, match => match.replace(';', ''));

  // 1. Fix commonly hallucinated broken nested brackets like A[{{Text}}] -> A{{"Text"}}
  code = code.replace(/([A-Za-z0-9_]+)\[\s*\{\{\s*([^}]+)\s*\}\}\s*\]/g, '$1{{"$2"}}');
  code = code.replace(/([A-Za-z0-9_]+)\[\s*\(\(\s*([^)]+)\s*\)\)\s*\]/g, '$1(("$2"))');
  code = code.replace(/([A-Za-z0-9_]+)\[\s*\[\s*\(\s*([^)]+)\s*\)\s*\]\s*\]/g, '$1[["$2"]]'); // A[[(Text)]] -> A[["Text"]]
  code = code.replace(/([A-Za-z0-9_]+)\(\s*\[\s*\[\s*([^\]]+)\s*\]\s*\]\s*\)/g, '$1[["$2"]]'); // A([[Text]]) -> A[["Text"]]

  // 2. Wrap all standard node shapes' text in quotes to prevent ANY syntax errors from special characters
  // Square: A[Text] -> A["Text"]
  code = code.replace(/([A-Za-z0-9_]+)\[([^"\[({/\\][^\]]*)\]/g, (match, id, text) => `${id}["${text.trim().replace(/"/g, "'")}"]`);
  
  // Cylinder: A[(Text)] -> A[("Text")]
  code = code.replace(/([A-Za-z0-9_]+)\[\(\s*([^")]+?)\s*\)\]/g, (match, id, text) => `${id}[("${text.replace(/"/g, "'")}")]`);
  
  // Subroutine: A[[Text]] -> A[["Text"]]
  code = code.replace(/([A-Za-z0-9_]+)\[\[\s*([^"\]]+?)\s*\]\]/g, (match, id, text) => `${id}[["${text.replace(/"/g, "'")}"]]`);
  
  // Stadium: A([Text]) -> A(["Text"])
  code = code.replace(/([A-Za-z0-9_]+)\(\[\s*([^"\]]+?)\s*\]\)/g, (match, id, text) => `${id}(["${text.replace(/"/g, "'")}"])`);
  
  // Circle/Double Circle: A((Text)) -> A(("Text"))
  code = code.replace(/([A-Za-z0-9_]+)\(\(\s*([^")]+?)\s*\)\)/g, (match, id, text) => `${id}(("${text.replace(/"/g, "'")}"))`);
  
  // Round: A(Text) -> A("Text")
  code = code.replace(/([A-Za-z0-9_]+)\(([^"([][^)]*)\)/g, (match, id, text) => `${id}("${text.trim().replace(/"/g, "'")}")`);
  
  // Fix hallucinated triple braces BEFORE processing hexagons
  code = code.replace(/\{\{\{\s*"?([^"}]+?)"?\s*\}\}\}/g, '{{$1}}');
  
  // Hexagon: A{{Text}} -> A{{"Text"}}
  code = code.replace(/([A-Za-z0-9_]+)\{\{\s*([^"}]+?)\s*\}\}/g, (match, id, text) => `${id}{{"${text.replace(/"/g, "'")}"}}`);
  
  // Rhombus: A{Text} -> A{"Text"}
  code = code.replace(/([A-Za-z0-9_]+)\{([^"{][^}]*)\}/g, (match, id, text) => `${id}{"${text.trim().replace(/"/g, "'")}"}`);

  // Fix invalid subgraph titles (e.g., subgraph DMZ "DMZ Zone" -> subgraph DMZ ["DMZ Zone"])
  code = code.replace(/subgraph\s+([a-zA-Z0-9_-]+)\s+"([^"]+)"/gim, 'subgraph $1 ["$2"]');

  // Fix bare quoted subgraphs (e.g., subgraph "Command and Control" -> subgraph Command_and_Control ["Command and Control"])
  code = code.replace(/^(\s*subgraph\s+)"([^"]+)"\s*$/gim, (match, prefix, title) => {
    return prefix + title.replace(/\s+/g, '_') + ' ["' + title + '"]';
  });

  // Fix subgraphs with spaces in the ID (e.g. subgraph Command and Control -> subgraph Command_and_Control)
  code = code.replace(/^(\s*subgraph\s+)([^\["{\n]+?)\s*$/gim, (match, prefix, idText) => {
    return prefix + idText.trim().replace(/\s+/g, '_');
  });
  
  // Strip ALL classDefs generated by LLM to prevent syntax errors
  code = code.replace(/^\s*classDef\s+.*$/gim, '');
  
  // Strip hallucinated CSS style lines (e.g. "style External padding:10px")
  code = code.replace(/^\s*style\s+[A-Za-z0-9_]+\s+[^;\n]+$/gim, '');
  
  // Strip direction statements inside subgraphs as they often crash specific Mermaid versions
  code = code.replace(/^\s*direction\s+(TB|TD|LR|RL|BT)\s*$/gim, '');
  
  // Safely quote subgraph titles to prevent any parsing crashes from special characters in translated titles
  code = code.replace(/subgraph\s+([A-Za-z0-9_-]+)\s*\[([^"\]]+)\]/gim, 'subgraph $1 ["$2"]');
  
  // Process line by line to ensure absolute robustness
  let lines = code.split('\n').map(l => l.trimEnd());
  
  // Find the actual start of the diagram
  let startIndex = lines.findIndex(l => /^\s*(flowchart|graph|mindmap|pie|journey|gantt|sequenceDiagram|classDiagram)\b/i.test(l));
  
  if (startIndex === -1) {
    // If we still can't find a valid declaration, it's garbage text.
    // Let's try to find the first line that looks like a node definition or edge
    const firstNodeIdx = lines.findIndex(l => /^[A-Za-z0-9_]+\[/.test(l.trim()) || /-->/.test(l));
    if (firstNodeIdx !== -1) {
      lines = lines.slice(firstNodeIdx);
    } else {
      // Just take everything that isn't empty
      lines = lines.filter(l => l.trim().length > 0);
    }
    lines = ['flowchart TD', ...lines];
    startIndex = 0;
  }
  
  // Drop any conversational text before the diagram
  lines = lines.slice(startIndex);
  
  const diagramType = lines[0].trim().split(' ')[0].toLowerCase();
  
  // Only inject classDefs for flowcharts/graphs (mindmaps and others crash if classDefs are at the root)
  if (diagramType === 'flowchart' || diagramType === 'graph') {
    const classDefs = [
      'classDef malicious fill:#450a0a,stroke:#ef4444,color:#f87171,stroke-width:2px;',
      'classDef defensive fill:#052e16,stroke:#22c55e,color:#4ade80,stroke-width:2px;',
      'classDef neutral fill:#172554,stroke:#3b82f6,color:#60a5fa,stroke-width:2px;',
      'classDef external fill:#4a044e,stroke:#d946ef,color:#f0abfc,stroke-width:2px;',
      'classDef secure fill:#052e16,stroke:#22c55e,color:#4ade80,stroke-width:2px;',
      'classDef internal fill:#172554,stroke:#3b82f6,color:#60a5fa,stroke-width:2px;'
    ];
    lines.splice(1, 0, ...classDefs);
  } else if (diagramType === 'mindmap') {
    // Mindmaps will crash if the AI hallucinates :::class tags onto nodes. Strip them completely.
    lines = lines.map(l => l.replace(/:::[A-Za-z0-9_-]+/g, ''));
    // Mindmaps also crash if a node is just a double-quoted string without a shape wrapper. Strip the quotes.
    lines = lines.map(l => l.replace(/^(\s*)"([^"]+)"\s*$/, '$1$2'));
    // Also remove any inline quotes that might break standard text nodes
    lines = lines.map(l => {
      // If it has a shape wrapper like ((text)) or [text], leave it alone.
      if (l.match(/[{([].+?[})\]]/)) return l;
      // Otherwise strip double quotes from the line
      return l.replace(/"/g, '');
    });
    // Mindmaps WILL CRASH if there are parentheses () in the raw text. 
    // We must replace them with hyphens, EXCEPT for the root node which is intentionally root((Topic)).
    lines = lines.map(l => {
      if (l.includes('root((') || l.includes('root ((')) return l;
      return l.replace(/[()]/g, '-');
    });
  }

  // Globally fix double double-quotes that the AI sometimes hallucinates in flowcharts
  lines = lines.map(l => l.replace(/""/g, '"'));
  
  // The backend injects a `(Generated via GROQ...)` footer at the end of the JSON values. 
  // We MUST strip it out because it crashes Mermaid parsing!
  lines = lines.filter(l => !l.includes('(Generated via'));
  
  return lines.join('\n');
};

// Custom Mermaid Component
const MermaidDiagram = ({ chart }) => {
  const ref = React.useRef(null);
  
  React.useEffect(() => {
    if (ref.current && chart) {
      const cleanedChart = cleanMermaidCode(chart);
      
      if (!cleanedChart || cleanedChart.length < 10) {
        ref.current.innerHTML = `<div class="mermaid-error">No valid diagram code found in the generated output.</div>`;
        return;
      }
      
      mermaid.render('mermaid-' + Math.random().toString(36).substr(2, 9), cleanedChart).then(({ svg }) => {
        ref.current.innerHTML = svg;
        
        // Force text visibility in dark mode — mermaid's dark theme sometimes
        // leaves text elements with colors that blend into dark backgrounds
        const textElements = ref.current.querySelectorAll('text, .nodeLabel, .edgeLabel, .label');
        textElements.forEach(el => {
          const computed = window.getComputedStyle(el);
          const color = computed.color;
          const fill = computed.fill;
          // If text color is too dark (close to black), force it to light
          if (color === 'rgb(0, 0, 0)' || color === '#000000' || color === 'black' ||
              fill === 'rgb(0, 0, 0)' || fill === '#000000' || fill === 'black' ||
              fill === 'rgb(51, 51, 51)') {
            el.style.fill = '#e2e8f0';
            el.style.color = '#e2e8f0';
          }
        });
        
        // Also target spans inside foreignObjects (htmlLabels mode)
        const spans = ref.current.querySelectorAll('foreignObject span, foreignObject p, foreignObject div');
        spans.forEach(el => {
          el.style.color = '#e2e8f0';
        });
      }).catch(e => {
        console.error("Mermaid parsing error:", e);
        if (ref.current) {
          ref.current.innerHTML = `
            <div class="mermaid-error" style="padding: 16px; background: rgba(30, 41, 59, 0.5); border: 1px solid var(--border); border-radius: 8px;">
              <p style="color: var(--status-warning); font-weight: 600; margin-bottom: 12px;">⚠ Diagram rendering failed due to AI syntax hallucination</p>
              <pre style="text-align: left; padding: 16px; background: var(--bg-surface); border-radius: 8px; overflow: auto; font-size: 0.8125rem; color: var(--text-secondary); white-space: pre-wrap;">${cleanedChart}</pre>
            </div>`;
        }
      });
    }
  }, [chart]);
  
  return <div ref={ref} className="mermaid-container" />;
};




const OutputPage = () => {
  const navigate = useNavigate();
  const { t, language } = useLanguage();
  const { state, dispatch } = useApp();
  
  const activeOutputs = state.activeJobId ? state.generatedOutputs[state.activeJobId] : null;
  
  // Base list of all possible outputs
  const allOutputs = [
    { id: 'exec-summary', name: t('execSummary'), type: 'document', icon: FileBarChart, format: 'PDF' },
    { id: 'threat-advisory', name: t('threatAdvisory'), type: 'document', icon: FileText, format: 'PDF' },
    { id: 'pptx-deck', name: t('presentationDeck'), type: 'multimedia', icon: Presentation, format: 'PPTX' },
    { id: 'video-script', name: t('videoScript', 'Video Script'), type: 'document', icon: FileText, format: 'PDF' },
    { id: 'audio-briefing', name: t('audioBriefing'), type: 'multimedia', icon: Headphones, format: 'MP3' },
    { id: 'linkedin-post', name: t('linkedinPost'), type: 'social', icon: Share2, format: 'TXT' },
    { id: 'twitter-thread', name: t('twitterThread'), type: 'social', icon: Share2, format: 'TXT' },
    { id: 'arch-diagram', name: t('architectureDiagram'), type: 'visual', icon: GitBranch, format: 'SVG' },
    { id: 'flowchart', name: t('flowchartKillChain'), type: 'visual', icon: GitBranch, format: 'SVG' },
    { id: 'infographic', name: t('infographicLayout', 'Infographic'), type: 'visual', icon: GitBranch, format: 'SVG' }
  ];

  // Filter to only show what the user selected, and mark them as completed if we have LLM output
  const displayOutputs = state.selectedOutputs && state.selectedOutputs.length > 0 
    ? state.selectedOutputs.map(id => {
        const base = allOutputs.find(o => o.id === id);
        if (!base) return null;
        
        const hasContent = activeOutputs && activeOutputs[id];
        return {
          ...base,
          status: hasContent ? 'completed' : 'processing',
          progress: hasContent ? 100 : 50,
          fileSize: hasContent ? 'Generated' : null
        };
      }).filter(Boolean)
    : allOutputs.map(o => ({ ...o, status: 'completed', progress: 100, fileSize: 'Mock' }));

  // We map displayOutputs as our new mockOutputs variable so the rest of the file still works without major rewrites.
  const mockOutputs = displayOutputs;

  const [activePreview, setActivePreview] = useState('exec-summary');
  const [copied, setCopied] = useState(false);
  const [isPlaying, setIsPlaying] = useState(false);
  
  // Bundle export state
  const [isBundling, setIsBundling] = useState(false);
  const [bundleProgress, setBundleProgress] = useState(0);
  const [bundleComplete, setBundleComplete] = useState(false);

  const selectedItem = mockOutputs.find(o => o.id === activePreview) || mockOutputs[0];
  
  // Ensure activePreview matches selectedItem if it was out of sync
  React.useEffect(() => {
    if (selectedItem && selectedItem.id !== activePreview) {
      setActivePreview(selectedItem.id);
    }
  }, [selectedItem, activePreview]);

  const handleExportBundle = async () => {
    if (!activeOutputs) return;
    setIsBundling(true);
    setBundleProgress(10);
    setBundleComplete(false);
    
    try {
      const container = document.createElement('div');
      container.style.padding = '40px';
      container.style.fontFamily = 'system-ui, -apple-system, sans-serif';
      container.style.color = '#111827';
      container.style.lineHeight = '1.6';
      
      container.innerHTML = `
        <div style="text-align: center; margin-bottom: 50px; padding-bottom: 20px; border-bottom: 2px solid #3B82F6;">
          <h1 style="font-size: 32px; color: #1e293b; margin-bottom: 10px;">OmniForge Mission Package</h1>
          <p style="font-size: 16px; color: #64748b;">Generated on: ${new Date().toLocaleDateString()}</p>
        </div>
      `;

      const orderedIds = ['exec-summary', 'threat-advisory', 'infographic', 'flowchart', 'arch-diagram', 'pptx-deck', 'video-script', 'linkedin-post', 'twitter-thread'];
      
      for (let i = 0; i < orderedIds.length; i++) {
        const id = orderedIds[i];
        if (!activeOutputs[id]) continue;
        
        const content = activeOutputs[id];
        setBundleProgress(10 + Math.floor((i / orderedIds.length) * 50));
        
        const section = document.createElement('div');
        section.style.pageBreakInside = 'avoid';
        section.style.marginBottom = '40px';
        
        const itemConfig = mockOutputs.find(m => m.id === id);
        const sectionTitle = document.createElement('h2');
        sectionTitle.style.fontSize = '24px';
        sectionTitle.style.color = '#0f172a';
        sectionTitle.style.borderBottom = '1px solid #cbd5e1';
        sectionTitle.style.paddingBottom = '8px';
        sectionTitle.style.marginBottom = '20px';
        sectionTitle.innerText = itemConfig ? itemConfig.name : id;
        section.appendChild(sectionTitle);

        if (id === 'flowchart' || id === 'arch-diagram' || id === 'infographic') {
          const code = cleanMermaidCode(content);
          if (code && code.length > 10) {
            const svgContainer = document.createElement('div');
            svgContainer.style.background = '#ffffff'; 
            svgContainer.style.padding = '20px';
            svgContainer.style.borderRadius = '8px';
            svgContainer.style.border = '1px solid #e2e8f0';
            
            const hiddenDiv = document.createElement('div');
            hiddenDiv.style.visibility = 'hidden';
            hiddenDiv.style.position = 'absolute';
            document.body.appendChild(hiddenDiv);
            
            try {
              const { svg } = await mermaid.render('mermaid-bundle-' + Math.random().toString(36).substr(2, 9), code, hiddenDiv);
              let finalSvg = svg;
              if (!finalSvg.includes('xmlns="http://www.w3.org/2000/svg"')) {
                finalSvg = finalSvg.replace('<svg ', '<svg xmlns="http://www.w3.org/2000/svg" ');
              }
              finalSvg = finalSvg.replace(/style="max-width:[^"]+"/g, '');
              finalSvg = finalSvg.replace(/<svg([^>]+)>/, (match, p1) => {
                let newAttrs = p1.replace(/width="[^"]+"/, '').replace(/height="[^"]+"/, '');
                return `<svg ${newAttrs} width="100%" height="auto">`;
              });
              
              const svgStyles = `
                <style>
                  .node rect, .node circle, .node ellipse, .node polygon, .node path { fill: #f1f5f9 !important; stroke: #64748b !important; stroke-width: 1px !important; }
                  .node .label { color: #0f172a !important; font-family: sans-serif !important; fill: #0f172a !important; }
                  .edgeLabel { background-color: white !important; color: #0f172a !important; }
                  .cluster rect { fill: #f8fafc !important; stroke: #cbd5e1 !important; stroke-width: 1px !important; }
                  .cluster .label { fill: #334155 !important; font-weight: bold !important; }
                  .malicious rect, .malicious circle, .malicious polygon, .malicious path { fill: #fef2f2 !important; stroke: #ef4444 !important; stroke-width: 2px !important; }
                  .defensive rect, .defensive circle, .defensive polygon, .defensive path { fill: #f0fdf4 !important; stroke: #22c55e !important; stroke-width: 2px !important; }
                  .neutral rect, .neutral circle, .neutral polygon, .neutral path { fill: #eff6ff !important; stroke: #3b82f6 !important; stroke-width: 2px !important; }
                  .external rect, .external circle, .external polygon, .external path { fill: #fdf4ff !important; stroke: #d946ef !important; stroke-width: 2px !important; }
                  .secure rect, .secure circle, .secure polygon, .secure path { fill: #f0fdf4 !important; stroke: #22c55e !important; stroke-width: 2px !important; }
                  .internal rect, .internal circle, .internal polygon, .internal path { fill: #eff6ff !important; stroke: #3b82f6 !important; stroke-width: 2px !important; }
                </style>
              `;
              finalSvg = finalSvg.replace(/<svg[^>]*>/, (match) => match + svgStyles);
              
              svgContainer.innerHTML = finalSvg;
              section.appendChild(svgContainer);
            } catch (err) {
              console.error("Mermaid PDF error:", err);
            } finally {
              document.body.removeChild(hiddenDiv);
            }
          }
        } else {
          const html = marked(content);
          const mdContainer = document.createElement('div');
          mdContainer.innerHTML = html;
          
          const tables = mdContainer.querySelectorAll('table');
          tables.forEach(table => {
            table.style.width = '100%';
            table.style.borderCollapse = 'collapse';
            table.style.marginBottom = '20px';
          });
          const ths = mdContainer.querySelectorAll('th');
          ths.forEach(th => {
            th.style.border = '1px solid #cbd5e1';
            th.style.padding = '8px';
            th.style.backgroundColor = '#f1f5f9';
            th.style.textAlign = 'left';
          });
          const tds = mdContainer.querySelectorAll('td');
          tds.forEach(td => {
            td.style.border = '1px solid #cbd5e1';
            td.style.padding = '8px';
          });
          
          section.appendChild(mdContainer);
        }
        
        container.appendChild(section);
      }

      setBundleProgress(70);
      
      const opt = {
        margin:       0.5,
        filename:     `OmniForge_Mission_Package_${new Date().toISOString().slice(0,10)}.pdf`,
        image:        { type: 'jpeg', quality: 0.98 },
        html2canvas:  { scale: 2, useCORS: true },
        jsPDF:        { unit: 'in', format: 'letter', orientation: 'portrait' }
      };
      
      setBundleProgress(85);
      await html2pdf().set(opt).from(container).save();
      
      setBundleProgress(100);
      setTimeout(() => {
        setIsBundling(false);
        setBundleComplete(true);
        setTimeout(() => setBundleComplete(false), 4000);
      }, 500);

    } catch (e) {
      console.error("PDF generation failed:", e);
      setIsBundling(false);
    }
  };

  const handleDownload = (item) => {
    // Generate blob from activeOutputs if available
    const contentToDownload = activeOutputs && activeOutputs[item.id] ? activeOutputs[item.id] : `Mock content for ${item.name}`;
    
    // If it's supposed to be a PDF, generate a real PDF using html2pdf
    if (item.format === 'PDF') {
      const htmlContent = marked(contentToDownload);
      const container = document.createElement('div');
      container.innerHTML = htmlContent;
      // Basic styling for the PDF
      container.style.padding = '20px';
      container.style.fontFamily = 'system-ui, -apple-system, sans-serif';
      container.style.color = '#333';
      container.style.lineHeight = '1.6';
      
      const opt = {
        margin:       1,
        filename:     `${item.id}-omni-forge.pdf`,
        image:        { type: 'jpeg', quality: 0.98 },
        html2canvas:  { scale: 2 },
        jsPDF:        { unit: 'in', format: 'letter', orientation: 'portrait' }
      };
      
      html2pdf().set(opt).from(container).save();
      return;
    }

    if (item.format === 'PPTX') {
      const pres = new PptxGenJS();
      const slides = contentToDownload.split('---').map(s => s.trim()).filter(Boolean);
      
      slides.forEach(slideText => {
        const slide = pres.addSlide();
        
        // Basic parser: extract lines, if it starts with # or ## it's a title, otherwise body text
        const lines = slideText.split('\n');
        let title = '';
        let bodyLines = [];
        
        lines.forEach(line => {
          const l = line.trim();
          if (l.startsWith('#')) {
            // First header is the title
            if (!title) title = l.replace(/^#+\s*/, '').replace(/\*\*/g, '');
            else bodyLines.push(l);
          } else if (l) {
            bodyLines.push(l.replace(/^[-*]\s*/, '• ').replace(/\*\*/g, ''));
          }
        });
        
        if (title) {
          slide.addText(title, { x: 0.5, y: 0.5, w: '90%', h: 1, fontSize: 24, bold: true, color: '363636' });
          slide.addText(bodyLines.join('\n'), { x: 0.5, y: 1.5, w: '90%', h: 4, fontSize: 16, color: '666666', valign: 'top' });
        } else {
          slide.addText(bodyLines.join('\n'), { x: 0.5, y: 0.5, w: '90%', h: 5, fontSize: 16, color: '666666', valign: 'top' });
        }
      });
      
      pres.writeFile({ fileName: `${item.id}-omni-forge.pptx` });
      return;
    }
    
    // If it's supposed to be an MP3, fetch from our new TTS endpoint
    if (item.format === 'MP3') {
      const lang = language || 'en';
      const btn = document.querySelector('.download-actions'); // Just for UI indication in a real app, but we'll do it silently
      fetch(`/api/tts?text=${encodeURIComponent(contentToDownload.substring(0, 5000))}&lang=${lang}`)
        .then(res => res.json())
        .then(results => {
          // results is an array of { base64: "...", shortText: "..." }
          // We need to decode base64 strings into Uint8Arrays and concatenate them
          const arrays = results.map(r => {
            const binaryString = window.atob(r.base64);
            const len = binaryString.length;
            const bytes = new Uint8Array(len);
            for (let i = 0; i < len; i++) {
              bytes[i] = binaryString.charCodeAt(i);
            }
            return bytes;
          });
          
          let totalLength = arrays.reduce((acc, val) => acc + val.length, 0);
          let result = new Uint8Array(totalLength);
          let offset = 0;
          for (let arr of arrays) {
            result.set(arr, offset);
            offset += arr.length;
          }
          
          const blob = new Blob([result], { type: 'audio/mpeg' });
          const url = URL.createObjectURL(blob);
          const a = document.createElement('a');
          a.href = url;
          a.download = `${item.id}-omni-forge.mp3`;
          document.body.appendChild(a);
          a.click();
          document.body.removeChild(a);
          URL.revokeObjectURL(url);
        })
        .catch(err => console.error("MP3 Export error:", err));
      return;
    }

    // If it's supposed to be an SVG (Diagrams), render mermaid to SVG string and download
    if (item.format === 'SVG') {
      const code = cleanMermaidCode(contentToDownload);
      if (!code || code.length < 10) return;
      
      const container = document.createElement('div');
      container.style.visibility = 'hidden';
      container.style.position = 'absolute';
      container.style.width = '1600px';
      container.style.height = '1600px';
      document.body.appendChild(container);
      
      mermaid.render('mermaid-export-' + Math.random().toString(36).substr(2, 9), code, container)
        .then(({ svg }) => {
          let finalSvg = svg;
          // Add XML namespace if missing
          if (!finalSvg.includes('xmlns="http://www.w3.org/2000/svg"')) {
            finalSvg = finalSvg.replace('<svg ', '<svg xmlns="http://www.w3.org/2000/svg" ');
          }
          
          // Remove hardcoded styles and max-widths that ruin standalone viewing
          finalSvg = finalSvg.replace(/style="max-width:[^"]+"/g, '');
          // Force SVG to scale nicely
          finalSvg = finalSvg.replace(/<svg([^>]+)>/, (match, p1) => {
            // Strip existing width/height to avoid conflicts, then add 100%
            let newAttrs = p1.replace(/width="[^"]+"/, '').replace(/height="[^"]+"/, '');
            return `<svg ${newAttrs} width="100%" height="100%">`;
          });

          // Inject our custom CSS so the SVG looks identical to the web app
          const svgStyles = `
            <style>
              text { fill: #e2e8f0 !important; font-family: 'Inter', system-ui, sans-serif !important; font-size: 14px; font-weight: 500; }
              .node rect, .node polygon, .node circle, .node ellipse { stroke: #3b82f6 !important; stroke-width: 2px !important; }
              .edgePath .path { stroke: #64748b !important; stroke-width: 2px !important; }
              .edgePath .arrowheadPath { fill: #64748b !important; stroke: none !important; }
              .cluster rect { fill: rgba(15, 23, 42, 0.6) !important; stroke: #334155 !important; stroke-dasharray: 4; }
            </style>
          `;
          finalSvg = finalSvg.replace(/<svg[^>]+>/, match => match + svgStyles);

          const blob = new Blob([finalSvg], { type: 'image/svg+xml;charset=utf-8' });
          const url = URL.createObjectURL(blob);
          const a = document.createElement('a');
          a.href = url;
          a.download = `${item.id}-omni-forge.svg`;
          document.body.appendChild(a);
          a.click();
          document.body.removeChild(a);
          URL.revokeObjectURL(url);
          document.body.removeChild(container);
        })
        .catch(err => {
          console.error("SVG Export error:", err);
          if (document.body.contains(container)) document.body.removeChild(container);
        });
      return;
    }

    // Default for TXT and MD
    let extension = 'txt';
    const blob = new Blob([contentToDownload], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${item.id}-omni-forge.${extension}`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleCopy = () => {
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const togglePlay = () => {
    setIsPlaying(!isPlaying);
  };

  const handlePlayAudio = (text) => {
    if ('speechSynthesis' in window) {
      // Map language codes to TTS voices
      const getLangCode = (lang) => {
        if (lang === 'en') return 'en-US';
        return `${lang}-IN`; // Covers hi-IN, bn-IN, te-IN, mr-IN, ta-IN, gu-IN, kn-IN, ur-IN, etc.
      };
      
      const utterance = new SpeechSynthesisUtterance(text);
      const activeLang = language || 'en';
      utterance.lang = getLangCode(activeLang);
      
      // Ensure a native voice is picked if available
      const voices = window.speechSynthesis.getVoices();
      const targetVoice = voices.find(v => v.lang.startsWith(activeLang) || v.lang.startsWith(getLangCode(activeLang)));
      if (targetVoice) {
        utterance.voice = targetVoice;
      }
      
      utterance.onend = () => setIsPlaying(false);
      utterance.onerror = () => setIsPlaying(false);
      
      window.speechSynthesis.cancel(); // stop any current audio
      window.speechSynthesis.speak(utterance);
      setIsPlaying(true);
    } else {
      alert(t('tts_not_supported') || 'Text-to-Speech is not supported in this browser.');
    }
  };

  const handleStopAudio = () => {
    if ('speechSynthesis' in window) {
      window.speechSynthesis.cancel();
      setIsPlaying(false);
    }
  };

  const renderQueueItem = (item) => {
    const Icon = item.icon;
    const isCompleted = item.status === 'completed';
    const isProcessing = item.status === 'processing';

    return (
      <div key={item.id} className="queue-item">
        <div className="item-icon">
          <Icon size={20} />
        </div>
        
        <div className="item-info">
          <div className="item-name-row">
            <span className="item-name">{item.name}</span>
            <StatusBadge status={item.status} />
          </div>
          <div className="item-meta">
            <span className="item-format">{item.format}</span>
            {isCompleted && <span className="item-size">• {item.fileSize}</span>}
          </div>
          {isProcessing && (
            <div className="item-progress">
              <ProgressBar progress={item.progress} size="sm" showLabel={true} />
            </div>
          )}
        </div>

        <div className="item-actions">
          <button 
            className="action-btn"
            disabled={!isCompleted}
            onClick={() => isCompleted && setActivePreview(item.id)}
          >
            <Eye size={16} />
            Preview
          </button>
          <button 
            className={`action-btn ${isCompleted ? 'download' : ''}`}
            disabled={!isCompleted}
            onClick={() => handleDownload(item)}
          >
            <Download size={16} />
            Download
          </button>
        </div>
      </div>
    );
  };

  const renderExecutiveSummaryPreview = () => (
    <div className="doc-preview">
      <div className="doc-header">
        <div className="classification">{t('mockClassification')}</div>
        <h1>{t('mockExecSummaryTitle')}</h1>
        <p>{t('mockDate')}</p>
        <p>{t('mockReference')}</p>
      </div>
      
      <h2>{t('mockSituationOverview')}</h2>
      <p>{t('mockSituationText')}</p>
      
      <h2>{t('mockKeyFindings')}</h2>
      <ul>
        <li>{t('mockFinding1')}</li>
        <li>{t('mockFinding2')}</li>
        <li>{t('mockFinding3')}</li>
      </ul>

      <h2>{t('mockObservedIndicators')}</h2>
      <p>{t('mockIndicatorsText')}</p>
      <div style={{ display: 'flex', gap: '8px', flexWrap: 'wrap', marginBottom: '16px' }}>
        <span className="ioc-tag">192.168.45.21</span>
        <span className="ioc-tag">c2.midnight-operations[.]net</span>
        <span className="ioc-tag">SHA256: 8f4e3c...</span>
      </div>

      <h2>{t('mockRecommendations')}</h2>
      <p>{t('mockRecommendationsText')}</p>
    </div>
  );

  const renderSocialPreview = () => (
    <div className="social-preview">
      <div className="social-post">
        <div className="post-header">
          <div className="post-avatar">NT</div>
          <div>
            <div className="post-author">NTRO Cyber Intelligence</div>
            <div className="post-handle">@ntro_intel • 2h</div>
          </div>
        </div>
        <div className="post-body">
          ⚠️ URGENT ADVISORY: We have detected a coordinated campaign targeting critical infrastructure. Attackers are exploiting a zero-day vulnerability in popular edge devices to gain initial access.
          <br /><br />
          We strongly advise organizations to apply the latest security patches and monitor for unusual outbound DNS traffic.
          <br /><br />
          Full technical details and mitigations in our latest report.
          <div className="hashtags">
            #CyberSecurity #ThreatIntel #InfoSec #APT
          </div>
        </div>
      </div>
      <button className="copy-btn action-btn" onClick={handleCopy}>
        {copied ? <Check size={16} /> : <Copy size={16} />}
        {copied ? 'Copied!' : 'Copy to Clipboard'}
      </button>
    </div>
  );

  const renderAudioPreview = () => (
    <div className="audio-preview">
      <div className="audio-player">
        <div className="audio-controls">
          <button className="play-btn" onClick={togglePlay}>
            {isPlaying ? <Pause size={24} /> : <Play size={24} />}
          </button>
          <div className="audio-timeline">
            <span className="audio-time">1:15</span>
            <div className="timeline-bar">
              <div className="timeline-progress"></div>
            </div>
            <span className="audio-time">3:45</span>
          </div>
          <Volume2 size={20} className="text-secondary" />
        </div>
        
        <div className="waveform">
          {[...Array(40)].map((_, i) => {
            const height = Math.floor(Math.random() * 80) + 20;
            const delay = Math.random() * 0.5;
            return (
              <div 
                key={i} 
                className="wave-bar" 
                style={{ 
                  height: `${height}%`,
                  animationPlayState: isPlaying ? 'running' : 'paused',
                  animationDelay: `${delay}s`
                }} 
              />
            );
          })}
        </div>
      </div>
    </div>
  );

  const renderDiagramPreview = () => (
    <div className="diagram-preview">
      <div className="kill-chain">
        <div className="chain-step">Reconnaissance</div>
        <div className="chain-arrow"><ArrowRight size={16} /></div>
        <div className="chain-step">Weaponization</div>
        <div className="chain-arrow"><ArrowRight size={16} /></div>
        <div className="chain-step">Delivery</div>
        <div className="chain-arrow"><ArrowRight size={16} /></div>
        <div className="chain-step">Exploitation</div>
        <div className="chain-arrow"><ArrowRight size={16} /></div>
        <div className="chain-step">Installation</div>
        <div className="chain-arrow"><ArrowRight size={16} /></div>
        <div className="chain-step">C2</div>
        <div className="chain-arrow"><ArrowRight size={16} /></div>
        <div className="chain-step" style={{ borderColor: 'var(--status-danger)'}}>Actions</div>
      </div>
      <p style={{ color: 'var(--text-secondary)', fontSize: '0.875rem', marginTop: '16px', textAlign: 'center' }}>
        APT-Midnight Attack Flow Diagram
      </p>
    </div>
  );

  const getPreviewContent = () => {
    if (!selectedItem) return null;

    let text = activeOutputs && activeOutputs[selectedItem.id] 
      ? activeOutputs[selectedItem.id] 
      : 'Error: Content not found or still generating.';

    // Check for Presentation Deck split
    if (activePreview === 'pptx-deck') {
      const slides = text.split('---').map(s => s.trim()).filter(Boolean);
      return (
        <div className="presentation-grid" style={{ display: 'grid', gap: '24px', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))' }}>
          {slides.map((slide, i) => (
            <div key={i} className="presentation-slide" style={{ background: 'var(--surface-color)', padding: '24px', borderRadius: '8px', border: '1px solid var(--border-color)', minHeight: '200px' }}>
              <ReactMarkdown remarkPlugins={[remarkGfm]}>{slide}</ReactMarkdown>
            </div>
          ))}
        </div>
      );
    }

    if (activePreview === 'flowchart' || activePreview === 'arch-diagram' || activePreview === 'infographic') {
      return (
        <div className="preview-document" style={{ position: 'relative', height: '100%', minHeight: '500px', background: 'var(--bg-surface)', padding: '24px', borderRadius: '12px' }}>
          <MermaidDiagram chart={text} />
        </div>
      );
    }

    // Video Script Player Simulation
    if (activePreview === 'video-script') {
      return (
        <div className="video-preview-container" style={{ borderRadius: '12px', overflow: 'hidden', border: '1px solid var(--border)' }}>
          <div className="video-player-mock" style={{ aspectRatio: '16/9', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', position: 'relative', overflow: 'hidden', background: '#020617' }}>
            
            {/* 100% Reliable CSS Radar Animation Background */}
            <div style={{ position: 'absolute', width: '200%', height: '200%', background: 'radial-gradient(circle, rgba(16,185,129,0.1) 0%, rgba(2,6,23,1) 60%)', zIndex: 0 }} />
            <div style={{ position: 'absolute', width: '100vw', height: '100vw', maxWidth: '800px', maxHeight: '800px', border: '1px solid rgba(16,185,129,0.3)', borderRadius: '50%', zIndex: 0 }} />
            <div style={{ position: 'absolute', width: '100vw', height: '100vw', maxWidth: '600px', maxHeight: '600px', border: '1px solid rgba(16,185,129,0.2)', borderRadius: '50%', zIndex: 0 }} />
            <div style={{ position: 'absolute', width: '100vw', height: '100vw', maxWidth: '400px', maxHeight: '400px', border: '1px solid rgba(16,185,129,0.4)', borderRadius: '50%', zIndex: 0 }} />
            <div style={{ position: 'absolute', width: '50%', height: '50%', top: 0, right: '50%', transformOrigin: 'bottom right', background: 'linear-gradient(90deg, rgba(16,185,129,0) 0%, rgba(16,185,129,0.5) 100%)', zIndex: 0, animation: 'spin 4s linear infinite', borderRight: '2px solid rgba(16,185,129,0.8)' }} />
            <style>{`@keyframes spin { 100% { transform: rotate(360deg); } }`}</style>
            
            <div style={{ position: 'absolute', inset: 0, background: isPlaying ? 'rgba(15, 23, 42, 0.2)' : 'rgba(15, 23, 42, 0.7)', zIndex: 1, transition: 'background 0.5s' }} />
            
            {!isPlaying && (
              <div style={{ position: 'relative', zIndex: 2, textAlign: 'center' }}>
                <button 
                  className="play-button" 
                  onClick={() => handlePlayAudio(text)} 
                  disabled={isPlaying} 
                  style={{ background: 'var(--primary)', border: 'none', borderRadius: '50%', width: '72px', height: '72px', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', margin: '0 auto 16px', transition: 'transform 0.2s', boxShadow: '0 4px 12px rgba(0,0,0,0.5)' }}
                  onMouseOver={(e) => e.currentTarget.style.transform = 'scale(1.05)'}
                  onMouseOut={(e) => e.currentTarget.style.transform = 'scale(1)'}
                >
                  <span style={{ color: 'white', fontSize: '32px', marginLeft: '6px' }}>▶</span>
                </button>
                <h3 style={{ color: '#fff', margin: 0, fontWeight: 600, fontSize: '1.25rem', textShadow: '0 2px 4px rgba(0,0,0,0.5)' }}>AI Video Storyboard</h3>
                <p style={{ color: '#cbd5e1', fontSize: '0.875rem', marginTop: '8px', textShadow: '0 1px 2px rgba(0,0,0,0.5)' }}>Press play to preview generated narration</p>
              </div>
            )}
            
            {isPlaying && (
              <div style={{ position: 'absolute', bottom: '24px', left: '24px', right: '24px', background: 'rgba(0,0,0,0.85)', padding: '16px', borderRadius: '8px', borderLeft: '4px solid var(--primary)', backdropFilter: 'blur(4px)', zIndex: 2 }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '8px' }}>
                  <div className="audio-wave" style={{ display: 'flex', gap: '3px', height: '16px' }}>
                    <div style={{ width: '3px', height: '100%', background: 'var(--primary)', animation: 'pulse 1s infinite' }}></div>
                    <div style={{ width: '3px', height: '60%', background: 'var(--primary)', animation: 'pulse 1.2s infinite' }}></div>
                    <div style={{ width: '3px', height: '80%', background: 'var(--primary)', animation: 'pulse 0.8s infinite' }}></div>
                  </div>
                  <p style={{ color: '#38bdf8', margin: 0, fontSize: '0.875rem', fontWeight: 600 }}>Synthesizing and playing AI voice narration...</p>
                </div>
                <button onClick={handleStopAudio} style={{ background: 'transparent', border: '1px solid #ef4444', color: '#ef4444', padding: '4px 12px', borderRadius: '4px', fontSize: '0.75rem', cursor: 'pointer' }}>Stop Playback</button>
              </div>
            )}
          </div>
          <div className="video-script-text" style={{ padding: '32px', background: 'var(--bg-surface)', maxHeight: '500px', overflowY: 'auto' }}>
            <ReactMarkdown remarkPlugins={[remarkGfm]}>{text}</ReactMarkdown>
          </div>
        </div>
      );
    }

    return (
      <div className="preview-document" style={{ position: 'relative' }}>
        {activePreview === 'audio-briefing' && (
          <div className="audio-controls" style={{ display: 'flex', gap: '12px', marginBottom: '24px', padding: '12px', background: 'var(--surface-color)', borderRadius: '8px' }}>
            <button className="action-btn" onClick={() => handlePlayAudio(text)} disabled={isPlaying}>
              ▶ Play Briefing
            </button>
            <button className="action-btn" onClick={handleStopAudio} disabled={!isPlaying}>
              ⏹ Stop
            </button>
          </div>
        )}
        <ReactMarkdown 
          remarkPlugins={[remarkGfm]}
          components={{
            code({node, inline, className, children, ...props}) {
              const match = /language-(\w+)/.exec(className || '');
              if (!inline && match && (match[1] === 'mermaid' || match[1] === 'flowchart')) {
                return <MermaidDiagram chart={String(children).replace(/\n$/, '')} />;
              }
              return <code className={className} {...props}>{children}</code>;
            }
          }}
        >
          {text}
        </ReactMarkdown>
      </div>
    );
  };

  const completedCount = mockOutputs.filter(o => o.status === 'completed').length;

  return (
    <div className="output-page">
      <div className="output-header">
        <h1>Generated Deliverables</h1>
        <p>{t('outputDesc')}</p>
      </div>

      <div className="queue-section">
        <div className="queue-header">
          <h3>{t('generationQueue')}</h3>
          <span className="text-secondary" style={{ fontSize: '0.875rem' }}>
            {completedCount} {t('of')} {mockOutputs.length} completed
          </span>
        </div>
        
        <div className="queue-list">
          {mockOutputs.map(renderQueueItem)}
        </div>
      </div>

      <div className="preview-section">
        <div className="preview-tabs">
          {mockOutputs.map(item => (
            <button 
              key={item.id}
              className={`preview-tab ${activePreview === item.id ? 'active' : ''}`}
              onClick={() => setActivePreview(item.id)}
            >
              {item.name}
            </button>
          ))}
        </div>
        
        <div className="preview-content">
          {getPreviewContent()}
        </div>
      </div>

      <div className="download-bar">
        <div className="download-stats">
          <strong>{completedCount} {t('of')} {mockOutputs.length} deliverables ready</strong>
          <p className="text-secondary" style={{ fontSize: '0.875rem', margin: 0 }}>All files will be packaged as a ZIP archive.</p>
        </div>
        <div className="download-actions" style={{ display: 'flex', gap: '16px' }}>
          <button className="regenerate-btn" onClick={() => navigate('/transform')}>
            <RefreshCw size={18} />
            Regenerate All
          </button>
          <button className="download-all-btn" onClick={handleExportBundle}>
            <Download size={18} />
            Download All Completed
          </button>
        </div>
      </div>

      <section className="bundle-section">
        <div className="bundle-card">
          <div className="bundle-header">
            <div className="bundle-icon">
              <Package size={24} />
            </div>
            <div className="bundle-info">
              <h3 className="bundle-title">Export Mission Package</h3>
              <p className="bundle-desc">Bundle all completed deliverables into a single downloadable archive (.zip)</p>
            </div>
          </div>
          
          <div className="bundle-contents">
            <h4 className="bundle-contents-title">Package Contents:</h4>
            <div className="bundle-file-list">
              {mockOutputs.filter(o => o.status === 'completed').map(output => (
                <div key={output.id} className="bundle-file-item">
                  <output.icon size={14} />
                  <span>{output.name}</span>
                  <span className="bundle-file-format">{output.format}</span>
                  <span className="bundle-file-size">{output.fileSize}</span>
                </div>
              ))}
            </div>
          </div>

          {isBundling && (
            <div className="bundle-progress">
              <div className="bundle-progress-header">
                <span className="bundle-progress-label">Compiling archive...</span>
                <span className="bundle-progress-percent">{bundleProgress}%</span>
              </div>
              <div className="bundle-progress-bar">
                <div className="bundle-progress-fill" style={{ width: `${bundleProgress}%` }}></div>
              </div>
              <div className="bundle-progress-steps">
                <span className={bundleProgress >= 15 ? 'step-done' : ''}>Collecting files</span>
                <span className={bundleProgress >= 48 ? 'step-done' : ''}>Compressing</span>
                <span className={bundleProgress >= 78 ? 'step-done' : ''}>Encrypting</span>
                <span className={bundleProgress >= 100 ? 'step-done' : ''}>Finalizing</span>
              </div>
            </div>
          )}

          {bundleComplete && (
            <div className="bundle-success">
              <Check size={18} />
              <span>Mission package ready — OmniForge_Bundle_2026-09-13.zip (324 KB)</span>
            </div>
          )}

          <button 
            className={`bundle-export-btn ${isBundling ? 'bundling' : ''} ${bundleComplete ? 'complete' : ''}`}
            onClick={handleExportBundle}
            disabled={isBundling}
          >
            {isBundling ? (
              <><Loader2 size={18} className="btn-spinner" /> Compiling Package...</>
            ) : bundleComplete ? (
              <><Check size={18} /> Download Package</>
            ) : (
              <><Package size={18} /> {t('exportMissionPackage')}</>
            )}
          </button>
        </div>
      </section>
    </div>
  );
};

export default OutputPage;
